name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: Sync dependencies
        run: rye sync
      - name: Lint
        run: |
          rye fmt --check
          rye lint
      - name: Tests
        run: |
          rye run ci:test
